### ISSUE TITLE
Upgrade falafel to 1.0.0?

### ISSUE THREAD

**Issue by shesek** [substack/bundle-collapser#11]
The current version of falafel uses bundleDepdendecies, which [does not work properly](https://github.com/substack/node-falafel/issues/28) with shrinkwrap due to an [npm bug](https://github.com/npm/npm/issues/2147).

The usage of bundleDepdendecies was removed in falafel 1.0.0, which should fix this issue, but I'm not sure whether its compatible with bundle-collapser. Is it?

**Comment by shesek** [comment]
Also related: https://github.com/substack/node-falafel/pull/29

**Comment by substack** [comment]
Falafel version upgraded in bundle-collapser 1.1.4.
