### ISSUE TITLE
Option to enable `allowReturnOutsideFunction`

### ISSUE THREAD

**Issue by binarykitchen** [substack/bundle-collapser#14]
To suppress the problem described in https://github.com/marijnh/acorn/issues/259, I need to set `allowReturnOutsideFunction` to true for acorn.

Any chance we can introduce such a new option to the bundle-collapser, and have it passed through falafel to acorn? I know, it's not ideal but how else can I tell acorn to behave differently?

**Comment by substack** [comment]
This feature would be upstream in [browser-unpack](https://npmjs.com/package/browser-unpack).

**Comment by substack** [comment]
Fixed in 1.2.1. I also added a test to the suite.

**Comment by binarykitchen** [comment]
thx 4 that super-fast update, all good now
