### ISSUE TITLE
Handle await/async

### ISSUE THREAD

**Issue by sassanh** [substack/bundle-collapser#22]
Newer versions of Chrome support await/async so I don't wanna use polyfills for that, but then I can't use bundle-collapser, I guess upgrading dependencies (browser-pack, browser-unpack) to latest versions should solve the issue.

**Comment by yoshuawuyts** [comment]
yup, that should do the trick (:

**Comment by sassanh** [comment]
I can create a PR if @substack confirms upgrading dependencies solves it.

**Comment by sassanh** [comment]
It's solved in new version of `bundle-collapser`
